name: build
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: yarn --ignore-scripts
        shell: bash 
        
      - name: Run Tests
        run: yarn hardhat coverage --network hardhat
        env:
          MNEMONIC: ${{ secrets.MNEMONIC }}
          PRIVATEKEY: ${{ secrets.PRIVATEKEY }}
          
      - name: Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
